### ISSUE TITLE
No Lootr  chests for Pirates & looters

### ISSUE THREAD

**Issue by Slither88** [noobanidus/Lootr#10]
Hi I am using 1.16.4 with forge 35.1.37 and version 1.16.4-0.0.4.11 of Lootr.

As far as I can tell the chests for Pirates and looters are just normal chests.

https://www.curseforge.com/minecraft/mc-mods/pirates-and-looters-mod

**Comment by noobanidus** [comment]
Unfortunately, this is an all-rights-reserved mod and the source isn't visible. The only thing I can suggest is contacting the author and ensuring that they're using the static `LockableLootTileEntity::setLootTable` method instead of interacting directly with the tile, as Lootr is unable to catch the latter. 

Normally I would make a pull request myself to fix it, but in this instance, there's not really much I can do.

**Comment by Slither88** [comment]
Thank you for your efforts. I understand, I was not aware it was an mcreator mod. It does explain some things.

**Comment by noobanidus** [comment]
No worries! As far as I'm aware the MCreator license previously prevented authors from modifying their code. This may have changed in the past year or so, but unfortunately I don't see much chance -- or a way to contact the author directly.

**Comment by Slither88** [comment]
That is fine. I was wondering why the trees it adds does not drop saplings when harvested. Now I know. Its not a bad mod, it works on a server and has not been the cause of a crash, but I know that mcreator mods are like homemade bread by an amateur cook, never know if the center is fully cooked. I will just keep it as is for now. Its not that big of a deal. Players can be just like the pirates and plunder the loot before anyone else gets there.
