### ISSUE TITLE
1.12.2 Dispensers in jungle temples get turned into lootr chests

### ISSUE THREAD

**Issue by mxnmnm** [noobanidus/Lootr#117]

**Comment by embeddedt** [comment]
The reason this occurs is because of a design decision made to work around the lack of a `forge:chest` block tag in 1.12. There is now an option where the mod will try to convert any tile entity that has a loot table associated with it. That is enabled by default for 1.12. However, I forgot to consider that jungle temple dispensers are using a loot table...

There are two solutions I see here:

1. Since the `ADDITIONAL_CHESTS` config is a blacklist in this mode, I could add `minecraft:dispenser` to the blacklist by default. However, you specifically will still need to add it yourself since you already have a config generated.
2. Disable the tile entity replacement mode by default. This means that only vanilla chests will be converted. The main disadvantage of that is that I'll get bug reports about other loot chests not converting themselves like they would on 1.16.

I think solution 1 is probably better here; what do you think?

**Comment by mxnmnm** [comment]
Oh I see I didn't pay close attention to the config (I probably should have done that lmao) yea def the 1st one

**Comment by embeddedt** [comment]
Okay, that's what I've implemented in 0.3.0. Note that you'll still need to add the entry to the config yourself since you previously used an older version.
