### ISSUE TITLE
Crash on world creation with the last 2 versions of Lootr

### ISSUE THREAD

**Issue by Kangy1103** [noobanidus/Lootr#129]
Hi,
As far as I can tell Lootr is sometimes causing crashes when creating single player worlds.
I tried 0.2.18.55 & 0.2.17.54 on Forge 40.1.60.

Here are the 2 crash reports
[crash-2022-07-14_21.24.45-server.txt](https://github.com/noobanidus/Lootr/files/9115277/crash-2022-07-14_21.24.45-server.txt)
[crash-2022-07-14_21.44.57-server.txt](https://github.com/noobanidus/Lootr/files/9115278/crash-2022-07-14_21.44.57-server.txt)

Let me know if you need anything else from me :)

**Comment by noobanidus** [comment]
This is rather disturbing, because it looks like the world storage isn't available in the overworld... which is explicitly created *before* levels, etc. The only thing I can think of is that, somehow, the server tick is being triggered before this... 

If it's inconsistently happening, it might mean that this is a race condition and I need to add a "do nothing if no storage is found". If it's happening consistently, it might be something else.

Can you give me an idea of how frequently this is happening for you?

**Comment by Kangy1103** [comment]
Hi, I can consistently reproduce it every 2 or 3 worlds I create. I've downgraded Lootr to 0.2.16.53 and the crash happened once in around 10 worlds that I created
[crash-2022-07-14_22.25.10-server.txt](https://github.com/noobanidus/Lootr/files/9120148/crash-2022-07-14_22.25.10-server.txt)

**Comment by noobanidus** [comment]
Are you still having an issue with this?

**Comment by YumatanGames** [comment]
I'm having a crash on my server too, and although I'm not 100% sure it's lootr, it seems to be it. It doesn't usually happens on the world creation, but randomly at some point. I've being using chunky to simulate playing and when lootr is installed, at some point, I always have a crash. I'm yet to experience a similar crash without lootr installed.

I have two latest logs here:
[crash-2023-03-26_15.25.53-client.txt](https://github.com/noobanidus/Lootr/files/11073431/crash-2023-03-26_15.25.53-client.txt)
[crash-2023-03-26_16.00.14-server.txt](https://github.com/noobanidus/Lootr/files/11073432/crash-2023-03-26_16.00.14-server.txt)


I think this might be some sort of incompatibility with some mods that adds structures with loot, like the Yung's mods... But I'm also not sure.

**Comment by noobanidus** [comment]
The first client issue appears to be related to `com.jamieswhiteshirt.reachentityattributes`, I'm not sure what mod that's associated with, but that's a client-based crash rather than a server-based crash. I'm guessing something is not being loaded into the client.

The second issue, the server-based one, appears to be supplementaries attempting to load somethign from farmer's respite, which doesn't appear to be installed. I'm not sure if that's a farmer's respite issue (if you do have that installed), or a supplementaries issue. Specifically the second one is trying to load a class that doesn't exist -- it's possible that a version of farmer's respite has changed a class name or location, and the version of supplementaries hasn't been updated for that -- which would be bad compatibility code on supplementaries' side, they should really be using an API.

That said, the second issue is being triggered by a create contraption containing a fluid tank that's trying to interact with something.

Neither of them appear to be associated wtih Lootr, @YumatanGames.

**Comment by noobanidus** [comment]
I'm closing this issue as it doesn't appear to be replicable. Please file a new issue if you (@Kangy1103) experience this problem again in future versions (or if you are still experiencing it).
