### ISSUE TITLE
[1.12] Not all chests converted in Villages

### ISSUE THREAD

**Issue by Krutoy242** [noobanidus/Lootr#135]
Not every vanilla chest converted into Lootr ones in villages.
About 80% of chests are still vanilla.
`CONVERT_WORLDGEN_INVENTORIES` work inconsistent. It increase conversion rates, but some chests still unconverted.

Im playing [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack.

## Examples
`CONVERT_WORLDGEN_INVENTORIES=true`
There is village with house. This house generated by Recurrent Complex. There literally 3 chests converted and one don't.

![image](https://user-images.githubusercontent.com/936618/180262382-6456e7e2-6304-44dd-92c1-6713d355f93c.png)

![image](https://user-images.githubusercontent.com/936618/180263284-b48fbb44-033e-446b-8d27-66815f8667cb.png)

Unconverted chest have items in it:

![image](https://user-images.githubusercontent.com/936618/180263322-33c162df-a5d6-43cb-99ff-5fc01378a796.png)

There is another example. One house spawned with Lootr chests and other with vanilla:

![image](https://user-images.githubusercontent.com/936618/180264446-15033036-9c95-411b-b340-47b8c7e67c9f.png)
![image](https://user-images.githubusercontent.com/936618/180264529-90c794fe-3251-498b-82d0-a3719f93a19d.png)

I did it in new world and fly another 5000 blocks far. And there is still same buildings with one chest converted and other not:
![image](https://user-images.githubusercontent.com/936618/180266014-aeb14f51-27c4-4d40-b0bd-48ee97e5527a.png)

**Comment by noobanidus** [comment]
~~Unfortunately, the `/data` command wasn't added until 1.13. Can you confirm that the chests *do* indeed have a loot table associated with them? If they don't, then they aren't loot chests and won't be converted.~~

~~There are two ways to do this:~~

- ~~Open the chest and see if it contains anything (although this is not necessarily final as it may be a chest with items that are pre-determined).~~
- ~~Alternately, you could try opening it in spectator mode: if it's got a loot table, it should say "contents not generated yet" or something similar.~~
- ~~The more complex suggestion would be to use [the Coordinate Calculator for Minecraft](https://dinnerbone.com/minecraft/tools/coordinates/) to work out which region file these belong to, and then something like NBT Explorer to open that region file, find the relevant chunk and have a loot through the chests to see if they have `LootTable` in their NBT data.~~

~~Alternately, checking the recurrent complex structure file should tell you whether it has a loot table or not; I know recurrent complex did chests in a complex fashion that generated contents when the structure was placed, rather than using a loot table: this may be the issue.~~

I failed to notice that you specifically stated the chests had items in them, disregard.

**Comment by embeddedt** [comment]
The latest version of Lootr has custom support for Recurrent Complex loot tags, but I’m not sure if it will help in this case.

**Comment by noobanidus** [comment]
Please open a new issue if the latest version of Lootr for 1.12's Recurrent Complex support isn't sufficient.

**Comment by Krutoy242** [comment]
Ok, I will check it later. Week ago this problem was still actual.

**Comment by noobanidus** [comment]
As @embeddedt mentioned it's possible that hte newer version of Lootr for 1.12 might not be sufficient for Recurrent Complex. Unfortunately, it might just be something that you need to deal with, although I believe you could use the `/lootr custom` command (see the Wiki on commands) to convert the chests manually -- obviously this is non-ideal, but it's a potential solution.
