### ISSUE TITLE
Consider server-side only options

### ISSUE THREAD

**Issue by purejosh** [noobanidus/Lootr#158]
Due to the textures for the chests/barrels and such, this mod is required on the server and client. Have you considered enabling a version that wouldn't require it to be installed on the client? 

In that same thought process... would you consider ever releasing a plugin version of this? I can speak with personal experience that there are no good alternatives for this mod in a plugin form. I run both fabric and paper servers, and I love this mod. Just a thought for you.

**Comment by noobanidus** [comment]
Actually, it's required on both the server and the client because it introduces new blocks and new block entities into the game. The textures are simply part of that product; it would be possible to have a purely server-side version, but it would require a complete re-work of the codebase.

I've no experience writing plug-ins and unfortunately don't have the time to devote to learning it; I will say that the issues I experienced when first implementing it (in my attempts to keep it server-side) would still have to be surmounted when it comes to plug-ins and other plug-in/mod interactions.

**Comment by embeddedt** [comment]
It might be possible to run the Fabric version server side with PolyMc. I
think it’s designed for simple mods like this.

**Comment by unilock** [comment]
As a curiosity, I adapted Lootr to run entirely server-side using Polymer: https://github.com/unilock/PolyLootr
