### ISSUE TITLE
MyLootr -> Lootr Conversion

### ISSUE THREAD

**Issue by itsdinkd** [noobanidus/Lootr#184]
Hello.

I am writing out in relation to MyLootr and Lootr. I'd like to start using Lootr in my modpack, Another Quality Modpack 2.

Reason I am opening this because I was hoping you could create something that would allow me, and other modpack devs, if they wanted to replace MyLoot with Lootr. Can you create something that would basically convert any MyLoot chests into Lootr + the current loot table MyLoot had for that chest?

I tried using a mod that fixes the data registry and basically replaces blocks (I replaced myloot check with lootr chest) which worked, however, the lootr chests had no loot table.

**Comment by itsdinkd** [comment]
maybe a "refresh once" option?

**Comment by noobanidus** [comment]
So it looks like the MyLoot chests store their original Loot Table as "origLootTableId". You'd most likely have to translate this into "LootTable" in order to convert properly; if that's possible with your data registry/block replacement mod, that should do it for you.

Otherwise, this type of cross-mod interaction, especially with Fabric, is beyond me.
