### ISSUE TITLE
Lootr Chests accessable after they have been destroyed

### ISSUE THREAD

**Issue by Zelioth** [noobanidus/Lootr#200]
Minecraft 1.20.1
Forge 47.0.35
Lootr 0.7.30.73

Playing single player or server if you access a Lootr chest and the chest is destroyed you can still change its contents if you were in it prior to it being destroyted

This makes dungeons with traps that destroy chests useless since a player can still access the chest after it's been destroyed.

**Comment by WilliamBlaze** [comment]
Unfortunately that's a Minecraft bug that seems to happen with all forms of inventory containers, not just Lootr. However if the player who had opened said chest exits the chest's content menu after it's been destroyed, rest assured, it's impossible to re-access that screen again in all cases except for when server chunk updates are lagging.

Again, an issue that exists even in vanilla Minecraft. It doesn't render ALL traps useless, like the desert temple's TNT traps that are below the 4 loot chests - the player MIGHT luck out and be able to open one of the 4 chests in time to access its contents before the explosion destroys all 4 chests, but they wont be able to abuse this glitch/bug to access all 4 chest's inventories after the TNT trap has already detonated them to bits..

And this is all depending on how fast the multi-player server or one-player world updates its chunk data. the faster it updates, the greater chance that the game will go "oh! the container's gone already, so you cant access it's inventory since it no longer exists."

ya might not have noticed this issue sooner due to having a good computer or something to that effect, but for those of us who play minecraft off of digital dinosaurs -we tend to notice EVERYTHING that breaks due to lag. Lol.

**Comment by noobanidus** [comment]
Yes, this is an issue with the `stillValid` part of the container interface missing a check to make sure that the chest block entity still exists and is something I've been told of before but simply kept forgetting to do.

**Comment by noobanidus** [comment]
This is fixed for Forge 1.20 and 1.19.0/1.19.1/1.19.2.

**Comment by noobanidus** [comment]
Now available for Forge for 1.18.2.

**Comment by noobanidus** [comment]
This has also been side-ported to Fabric.
