### ISSUE TITLE
[1.18.2 Forge]Conversion stopped after a period of time

### ISSUE THREAD

**Issue by ghost** [noobanidus/Lootr#224]
I am using Lootr on a 1.18.2 Forge server. When I started the server, everything was normal, but after the player played for a period of time (all loot table containers were successfully converted to Lootr chests), the containers stopped converting to Lootr chests. After restarting the server, the containers that were not successfully converted before were successfully converted to Lootr boxes.
This is my log:
https://gist.github.com/sweetymajo/ea16a855f01ebf7ea95518536fb31250

I am not sure if there is any additional content required to address this issue. If there is any further content required, please let me know.

**Comment by noobanidus** [comment]
I'll have to make an issue about this and pin it. The most likely explanation is that the `maximum_age` default value (of 3 minutes) is too short.

`maximum_age` is how long from when a block entity is detected until it is removed from the conversion queue automatically. It stays in this queue until it's converted, which only happens once world generation has completed. 

If your TPS is low or world generation is laggy for whatever reason (especially after a server has been online for a long period of time), it will result in containers not being converted.

Logically I should increase the default to around 10 minutes (`20 * 60 * 10` instead of `20 * 60 * 3`), but unfortunately that doesn't help if you've already generated a configuration file.

So, the solution *should* be: change `maximum_age` to a higher value from what it currently is.

**Comment by noobanidus** [comment]
I've created a new pinned issue for this with more details. Please check out #226.
