### ISSUE TITLE
Lootr 1.20.1 [Watching Server]

### ISSUE THREAD

**Issue by DonorKrovi** [noobanidus/Lootr#234]
It took me a very long time to rebuild the build to find out what was causing my server to crash during world generation, I generated the world for about an hour, sometimes 20 minutes and the server would freeze and crash

lootr-1.20-0.7.30.73
https://mclo.gs/UNWJVCx
**I'm use Chunky mod** for pregeneration world

**Comment by noobanidus** [comment]
It's difficult to determine exactly what's going wrong here. For some reason the code is blocking on the main thread, which implies that chunks are being reported as ready, but then when Lootr begins replacnig (I think), it starts a block because chunk generation is ongoing.

I'd recommend disabling Lootr during chunk pregeneration. For all versions later than 1.12, Lootr functions retroactively, so it can be loaded after.

**Comment by DonorKrovi** [comment]
In that case, what should I turn off?
https://mclo.gs/sF2gW2b
