### ISSUE TITLE
Crash with mohist servertype and lootr

### ISSUE THREAD

**Issue by Xplodin** [noobanidus/Lootr#24]
Exception caught during firing event: Unknown entity class noobanidus.mods.lootr.entity.LootrChestMinecartEntity

crashlog: 
[crash-2021-02-25_21.05.25-server.txt](https://github.com/noobanidus/Lootr/files/6046987/crash-2021-02-25_21.05.25-server.txt)

Mohist is a bridge between forge and spigot/paper

**Comment by noobanidus** [comment]
Unfortunately, due to the complexity of Spigot/Paper/Bukkit/etc as well as any bridge services, there's no way for me to provide you with any assistance, especially as this just appears to be the existed of my custom Minecraft entity.

You'll probably need to file an issue on the Mohist project or one of the other relevant projects to get someone who actually even understands what the issue is.

Sorry I can't help!

**Comment by Xplodin** [comment]
All good. Thank you for looking into this!
I reported it to mohist, hopefully they fix.

**Comment by noobanidus** [comment]
Good luck! I wish I could do more to help.
