### ISSUE TITLE
Dungeon Crawl Loot Replaced

### ISSUE THREAD

**Issue by marcellonovak** [noobanidus/Lootr#261]
The dungeon crawl mod (https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl) generates chests without custom loot in them

**Comment by noobanidus** [comment]
Can you specify what version of Minecraft you're having this issue with, along with what version of Lootr?

**Comment by marcellonovak** [comment]
forge 1.19.2 43.3.7
lootr 0.4.25.65
dungeon crawl 2.3.12

**Comment by Saereth** [comment]
can confirm this is happening with dungeon crawl on NeoForge as well latest version of both mods on cf as of today

**Comment by noobanidus** [comment]
It's taken me a little while to get to this, but from what I can gather looking through the code, the issue seems to be that the `customPersistentData` is being discarded during conversion. I'm not sure if that will be the entire fix, but I'll include something in the next 1.20 release for Forge simply for testing purposes.

Unfortunately, the NeoForge/1.20.4/1.20.6 versions are quite a bit behind the main branch and will take a bit more effort.

**Comment by noobanidus** [comment]
@marcellonovak I believe this should be fixed with the latest release for 1.19.

@Saereth As above, this should be fixed for the 1.18.2, 1.19 and 1.20 releases. Unfortunately, with the 1.20.4 -> 1.20.6 release, I'm not entirely sure what I'm going to do with 1.20.4 releases -- as there's already a huge chunk of code that I still have to port.

**Comment by Saereth** [comment]
No worres, the pack im working on in neoforge 1.20.4 so whichever way you go is understandable, nice if it could get sorted but if not its not the end of the world
