### ISSUE TITLE
Chest Config?

### ISSUE THREAD

**Issue by TheLewtz** [noobanidus/Lootr#27]
So we are making a modpack and have ran into a problem.

We use a mod called Artifacts and one part of it has chest that are turned into mimics, which can then attack the player and drop items.  Now it seems the spawns of the mimic's are turned into lootr chest, thus not being able to be killed/attack the player.  

Not really sure on which side of the equation we need to try and adjust, just looking for help.

Think there might be some way to ignore "campsite" structures or something?  from artifacts?  What happens is the campsites spawn a chest (which gets turned into lootr chest), but sometimes they can spawn mimic instead.  and we haven't seen a mimic since adding in lootr.  Love your mod, it's great and we want to keep it, but we also really like artifacts.

Artifact mod:
https://www.curseforge.com/minecraft/mc-mods/artifacts

**Comment by noobanidus** [comment]
Two things first off: 

a) I'd confirm that using `/summon artifacts:mimic` or the relevant text accurately summons one.
b) They've recently added compatibility that makes their mimics use the Lootr skin if Lootr is installed.

Now, the primary thing here is: I don't control what spawns. If a chest or a barrel spawns and it's possible for me to replace it, I do so. This only happens if the specific calls are made to `setLootTable`. If a mod is calling `setLootTable` on a block, that says, to me, that the block is meant to be a chest or a barrel.

The decision about whether or not to spawn a mimic comes *much earlier* (or rather, it logically should, because to do so any later would be chaotic and hard to program) in this process -- before the best block is even placed, before `setLootTable` is even called. Indeed, `setLootTable` would never actually be called, because it would spawn an entity instead.

Thus my assumption is that, **chests are never turned into/converted into mimics, they were placed as mimics to begin with**, and that this is a process I can't inhibit.

As a side-note to this, I've been running Artifacts and Lootr together, internally, on my server, and have gotten a fair number of campsites. This is most likely due to the fact that YUNG's Better Caves causes them to spawn more frequently. I have also run into my fair number of mimic chests and been killed by what appears to be my own block.

So, possible answers here, in the form of questions:
a) Have you checked if Artifacts has changed their config in recent updates, perhaps they've added an option as to whether or not mimics spawn? (Unsure, kind of defeats the purpose of the mod)
b) How large is your sample size? How many campsites have you actually come across? What is the spawn rate of a mimic instead of a chest?

Tools for testing the presence of mimics would include `/forge entity list`, looking for `artifacts:mimic` (I presume). 

I would also recommend checking any mods that control monster spawning to make sure that mimics aren't somehow being prevented from spawning.

Beyond that, I'm afraid I'm not able to add much more. I'm about 98% sure that this is not something I could possibly cause with my code, simply due to how spawning an entity and placing a block are so difference.

My final comment is: if you're exploring the campsites in creative or spectator, make sure that you fly up closer to the chest to ensure that it *is* actually a Lootr chest and not actually a Lootr-flavoured chest mimic.

**Comment by TheLewtz** [comment]
Wow, that's an awesome reply.  I appreciate your time.  I'll dig in more and get back to you.

**Comment by noobanidus** [comment]
Hope it helps! Sorry if it's hard to read, I'm pretty tired but I wanted to get you something ASAP.

**Comment by noobanidus** [comment]
I was wondering if you'd heard any more about this?

**Comment by TheLewtz** [comment]
Negative.   Honestly. I've also been playing space engineers and not
minecraft.

**Comment by LTCatt** [comment]
Lootr is compatible with mimic in my integration package. The game generates a mimic with lootr chest's model, so I don't think it's lootr's problem?

**Comment by noobanidus** [comment]
As I haven't heard anything more on this, I'm just going to close it as I don't think it's an issue with Lootr.
