### ISSUE TITLE
[Feature Request] Color for Opened chest which still contains loot

### ISSUE THREAD

**Issue by Yourname942** [noobanidus/Lootr#29]
Minecraft 1.16.5
Forge 36.0.46
Lootr 1.16.4-0.0.4.16

It would be cool if instead of just turning grey/blue on  chest being opened, instead there could be a configureable option to have chests turn grey/blue on chest being empty for the player. 

Issue:
Players are moving the chests to a single room near their base which is fine for us, but the problem is when there is are massive wall(s) of them, it is hard to figure out which one was just opened, and which one still has loot in it. 

Proposed Solution:
Gold: unopened
Silver/some other color: opened but still contains loot 
the (blue/grey?) color: empty

**Comment by noobanidus** [comment]
As in, "still has original loot" or "still has items inside of it"? 

The latter is theoretically doable -- I could just change the colour of the gems -- but it also means that it someone dumps items inside of it, it would still count.

I'm not sure how feasible it would be to fully detect whether or not all of the items have been taken and it might be annoying if there's something crappy that you don't want to take out of a chest to have it still be marked...

So I guess completely empty makes more sense.

**Comment by noobanidus** [comment]
I'm unfortunately going to have to reject this request for now. It's going to triple the amount of data that needs to be stored/transmitted to the client, as there's no way for the client (which is what decides which skin to use) to actually see the contents of a chest (as Minecraft never transmits this information), so at the very least it would increase the amount of data transmitted.

I can think of a few ways around it, but I don't know that adding this level of complexity is necessarily something I want to do right now.

If I can think of an ideal/non-problematic solution or a very simple solution, I'll definitely go ahead with it. Otherwise, it's on the back-burner.
