### ISSUE TITLE
Incompatibility with Entity Model Features

### ISSUE THREAD

**Issue by Azzarg** [noobanidus/Lootr#296]
As long as the Entity Model features mod is installed, Lootr chests, and chests only, are invisible. They can still be opened, but are not visible except for the outline when selecting it. They are also invisible when held items, and invisible in the inventory.
![Screenshot 2024-02-18 094625](https://github.com/LootrMinecraft/Lootr/assets/89182296/5f789296-bb0f-47b5-acde-d4e7657a1100)

I tried fixing it by making a resource pack containing all the mod's assets, and I tried changing the version of Lootr, but that did not fix it.

**Comment by noobanidus** [comment]
So this appears to be an issue with EMF, although I'm not entirely sure how to approach it. I'm going to have a bit of a deeper dive into exactly what's happening, as I imagine it's something to do with the fact that they're mixing in to the model getter and handling it somehow.

They're expecting a context to be set whenever a `minecraft` model is used, in this case the chest/trapped chest, but we're not doing that because we're a mod. I'm not entirely sure how best to approach it.

**Comment by noobanidus** [comment]
My bad for assuming in this issue; once properly reported to the author of EMF, it looks as though they have implemented things to fix it. Not sure how long until the release, but good news!
