### ISSUE TITLE
[Bug] Nuclear bomb (explosion) from Alex's Caves breaks lootr barrels and minecarts with chests.

### ISSUE THREAD

**Issue by kitovoi111** [noobanidus/Lootr#403]
Nuclear bomb (explosion) from Alex's Caves breaks lootr barrels and minecarts with chests.

Version: Forge 1.19.2 & Forge 1.20.1

**Comment by kitovoi111** [comment]
I have Alex's Caves on 1.19.2 Forge, so the problem is very relevant.

**Comment by noobanidus** [comment]
So, the nuclear explosion breaking barrels looks to be an issue with Alex's Caves, they aren't checking blast resistance, it looks like they're just applying a carver.

I'll dig deeper into the Minecarts with chests, because they should be immune to the damage, unless it's classified as "bypasses_immune"...

EDIT: For Lootr blocks, you'll need to adjust the relevant tag:

```java
    private boolean isDestroyable(BlockState state) {
        return (!state.is(ACTagRegistry.NUKE_PROOF) && state.getBlock().getExplosionResistance() < AlexsCaves.COMMON_CONFIG.nukeMaxBlockExplosionResistance.get()) || state.is(ACBlockRegistry.TREMORZILLA_EGG.get());
    }
```

This tag appears to be `alexscaves:nuke_proof`.

**Comment by noobanidus** [comment]
Okay, I'm not sure how the nukes are bypassing the invulnerability, I'm assuming they must just be discarding minecarts.

[My relevant code](https://github.com/LootrMinecraft/Lootr/blob/1.19/src/main/java/noobanidus/mods/lootr/entity/LootrChestMinecartEntity.java#L99).
