### ISSUE TITLE
[Unrelated crash/Not Lootr] Lootr + The Graveyard Coffins crashes server.

### ISSUE THREAD

**Issue by MachMX** [noobanidus/Lootr#412]
Found out that Lootr and [The Graveyard](https://modrinth.com/mod/the-graveyard-forge) can cause server crashes. Doesn't seem to happen in all The Graveyard's structures or containers, mainly on **coffins.**
![image](https://github.com/LootrMinecraft/Lootr/assets/15898823/8b3651be-e2f3-455e-829f-c065ba5dd5fe)

I believe main issue is due to graveyard's coffins being treated as double chests containers and Lootr trying to generate loot for a single container (or similar). I managed to even bork the playerdata I was testing the issue on the server, but rollback was necessary tbh.

Recommending to completely disable Lootr integration into The Graveyard's structures or at least for corresponding loot table container (Graveyard Ruin containers seem to be fine).

_I am lazy, so I will just post one example:_
- graveyard:chests/small_graveyard_loot

mod versions used:
- Using Minecraft 1.20.1 with Prism Launcher / Forge 47.3.0
- lootr-forge-1.20-0.7.34.85.jar
- The_Graveyard_3.1_(FORGE)_for_1.20.1.jar

I saw this previous issue, which is kinda related.
https://github.com/LootrMinecraft/Lootr/issues/231

**Comment by noobanidus** [comment]
I'm confused as to how the player data could become corrupted. 

If it does cause crashes, could you please attach any crash logs?

**Comment by MachMX** [comment]
[crash-2024-06-28_06.10.22-server.log](https://github.com/user-attachments/files/16037500/crash-2024-06-28_06.10.22-server.log)
[crash-2024-06-28_06.00.42-server.log](https://github.com/user-attachments/files/16037501/crash-2024-06-28_06.00.42-server.log)
[crash-2024-06-28_06.22.45-server.log](https://github.com/user-attachments/files/16037502/crash-2024-06-28_06.22.45-server.log)

Got 3 of them. Altho most likely its now just the Chunk being corrupted. But all symptons go towards the same chunk with the affected graveyard structure. *will try to reset chunk with amulet when I get the downloaded world files on hand*

Its a very experimental mod setup as seen, but can say that no players have touched Create stuff yet (and only CTOV has some but should be off)

**Comment by noobanidus** [comment]
I'm pretty sure you can also use world edit to reset chunks on a server without having to download the world files.

**Comment by noobanidus** [comment]
So, when adding `graveyard:oak_coffin` to the `lootr:convert/chests` it seems to convert them "properly" although not in an ideal fashion: ![](https://i.imgur.com/rEV6rH6.png)

From the screenshot that you've posted, it doesn't look like any Lootr conversion has taken place -- by default the Graveyard coffins aren't converted.

So if you're getting crashes when opening them, I don't know if it's because of Lootr.

**Comment by MachMX** [comment]
*Found about WorldEdit later, will get that working, but thanks for reminder as I actually forgot*
At least it did happen but its avoidable with config settings, but tbh could have just been too many experimental stuff inside the setup colliding. (Including how for some reason Alex's Mobs' Bison were doing 13k ticks of lag by themselves). But yeah, those coffins seem to cause lots of bugs actually, so I am just blacklisting Graveyard overall to be safe. 


Also, server is stable now, did clear all saved player affected Lootr inventories just to be safe too.

**Comment by noobanidus** [comment]
@MachMX I'll repeat what I said before: the first picture you posted shows the Graveyard coffins in their original form; they have not been converted into Lootr containers (as demonstrated in the picture that I posted), so it is *not possible* for what you said to be true:

>  Lootr trying to generate loot for a single container (or similar)

There is no special integration with the Graveyard mod that would cause Lootr to do anything with the Graveyard containers. 

Blacklisting the Graveyard modid or the relevant loot tables will also do nothing as the blacklist system simply prevents containers from being converted to Lootr containers, and as I mentioned before, none of the Graveyard's containers should convert nor are any of them converted in the screenshot you posted.

All of the crash reports you posted are unrelated to Lootr.

If anything, I would be suspicious of using Sinytra Connector as it uses mixins to modify Forge and provide the Fabric API, and it is possible that some conflict is being caused by that.
