### ISSUE TITLE
Lootr incompatible with When Dungeons Arise

### ISSUE THREAD

**Issue by AnyaPizza** [noobanidus/Lootr#444]
lootr-fabric-1.20-0.7.33.81

On Fabric 1.20.1

Whenever I try to open a chest in the dungeons it gives me an error.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/b25db09d-2686-4136-8ed0-f996b3e8cef3">

**Comment by noobanidus** [comment]
This is an issue with When Dungeons Arise; this error message means that the loot table specified in the structure doesn't exist in the When Dungeons Arise data folder.

This likely means that the loot table was renamed or removed, and the structure hasn't been updated.

You'll need to report this to When Dungeons Arise.

In later versions I've improved the error message to make it clearer that the issue is with the mod in question, not with Lootr.
