### ISSUE TITLE
Lootr Chests on New World Creation

### ISSUE THREAD

**Issue by lemonelda** [noobanidus/Lootr#465]
So I am having an issue where the Lootr chests that spawn in the village I spawn at, do not open and say there is no loot table available. If I move about, say for example, 500 blocks to a new village, the chests work as they should. It is only the spawn chests in and around an area of about 100-400 blocks that seem to be affected.

I cannot open them, I have tried to refresh them all with game commands, and they still remain unopenable. I spawned in several chests and they all are afflicted with this. 

I don't know what to do, please advise. 

![image](https://github.com/user-attachments/assets/b1d17212-de55-4823-ab9a-8771fc28aa77)

**Comment by noobanidus** [comment]
What version of Minecraft are you playing, what mod loader and what version of Lootr are you using?

The "no loot table" available is a standard part of the Jade interface. There's Jade Integrations with Lootr, but I forget exactly which mod provides it.

However, please keep in mind that there is spawn protection, and blocks don't function the same within the spawn protection area. If your village is indeed the spawn area, check to make sure that spawn protection isn't an issue; try opening them in creative mode, for example. This would potentially have the effect of not being able to open containers.

**Comment by lemonelda** [comment]
> What version of Minecraft are you playing, what mod loader and what version of Lootr are you using?
> 
> The "no loot table" available is a standard part of the Jade interface. There's Jade Integrations with Lootr, but I forget exactly which mod provides it.
> 
> However, please keep in mind that there is spawn protection, and blocks don't function the same within the spawn protection area. If your village is indeed the spawn area, check to make sure that spawn protection isn't an issue; try opening them in creative mode, for example. This would potentially have the effect of not being able to open containers.

I am on Forge, 1.20.1, the modloader I am using is Prism,  and I am using 0.7.34.87 Lootr version. I will look and see if I can fidn the Jade integration modd for Lootr and report back if that helped the issue!

**Comment by lemonelda** [comment]
So I unenabled Jade and Jade Addons to see if that was the issue, and unfortunately the same issue is still happening when I try to open chests in my spawned village area. Everything that I can interact with i.e blocks, crafting tables and other ui based blocks, are working. It's just the Lootr chests in my spawn point that don't work. I did try Creative mode and it was still happening.

Update: I also removed village spawn point mod thinking there might be incompatibility, and its still not working.

**Comment by noobanidus** [comment]
So to clarify what I meant:

- Jade and Jade Addons are not going to be the cause of the problem. If you haven't opened the chest yet, you will get "loot not generated" regardless (I believe)
- The default "loot not generated" whenever looking at a Lootr chest is generally a result of the mod seeing that the container has a loot table still, which, for Vanilla containers, means that loot *is not generated*: in Vanilla, when it generates loot, it removes the loot table to prevent it from generating again. Lootr *does not* remove the loot table.
- I'm not sure how the Village spawn mod functions, but if it ensures that spawn is placed at a village, that also means *spawn protection* will be applied to that village. Removing the Village spawn mod would not have any effect.

> If I move about, say for example, 500 blocks to a new village, the chests work as they should.

The question is here whether or not [*spawn protection*](https://minecraft.fandom.com/wiki/Spawn_protection) is applying in this area. Spawn protection generally prevents *anyone* who doesn't have permission from interacting with blocks, but only applies to a specific area, and *should not do anything in single-player* (you appear to be in single player).

Are you able to open these chests in creative mode? That should bypass any potential spawn protection.

Are there any other mods installed that could potentially affect things? 

The fact that chests are working outside of this area leads me to believe that Lootr isn't the issue.

If you aren't in single-player, you can disable spawn protection in the server properties and that should fix it.

Otherwise, if you could upload a copy of your logs when you try to interact with the blocks, that would be helpful. Further, using `/data get block` while looking at a chest and then using the <Tab> key to complete the coordinates and taking a screenshot of the result would help me diagnose the issue further.
