### ISSUE TITLE
Loot not generating after world update

### ISSUE THREAD

**Issue by DudeMcBroGuy** [noobanidus/Lootr#488]
I just updated my world from an older version of Prominence 2 to a newer one (both are 1.20.1) and on certain containers I get this message: "The loot table for this container resolved to empty and loot could not be generated." I don't see any other issues posted online talking about it and am wondering if anyone else is having this issue and if there is a fix for it. I've added the snippet from the latest log. Thank you!
![image](https://github.com/user-attachments/assets/d1aa33b6-012a-4c47-8878-cff6dd9a26f2)
![image](https://github.com/user-attachments/assets/51af5258-f7b9-49a3-865d-48c061225a1c)

**Comment by noobanidus** [comment]
This sounds as though a mod has been removed or a loot table has been changed. The issue is with the `fishofthieves` mod no longer having the `chests/seapost_barrel_firework` loot table in it. 

It's not an issue with Lootr and unfortunately not one I can help resolve. I'd suggest checking out the Discord associated with that mod pack for help.
