### ISSUE TITLE
[Suggestion] Automatically disabled in single player

### ISSUE THREAD

**Issue by Ironnoob73** [noobanidus/Lootr#489]
Many modpacks install this mod. If it is a single-player game, many features of this mod will become troublesome, such as directly destroying the loot chests will cause the loot inside to not be generated, and the chest minecart cannot be removed at all in some cases.

**Comment by noobanidus** [comment]
There's now a configuration option that allows you to generate loot and drop it when you break a container. I'll look into a similar feature for when destroying minecarts at some point in the future.

Otherwise, you can manually disable the mod from loading. 

I've no plan to make this an automatic thing as this isn't something that has been requested frequently enough.
