### ISSUE TITLE
[1.16.5] Battle Tower Golem Explosions destroys lootr chests

### ISSUE THREAD

**Issue by MystiaTech** [noobanidus/Lootr#76]
Using Lootr 0.1.11.36 and Battle Tower Lite (Forge) on Forge 36.2.21,

The Golem's explosion will destroy the chest from Lootr according to testers of my modpack. 

I haven't attempted to replicate it myself but I figure I should bring the issue up to you in case this was not intended

**Comment by noobanidus** [comment]
Unfortunately, this is an MCreator mod and quite difficult to understand.

~~From looking through the code, it uses the `BREAK` type of explosion, which implies that this functionality was desired. I'm hesitant to add an exclusion or blast resistance as this would render TNT somewhat useless.~~

~~An option is to make the normal chest blast resistant, but to leave the trapped chest susceptible to explosions. I'm not sure at this point what option would be best.~~

Thinking about this, that's not actually possible, as the "trap" in the desert pyramid is triggered by a pressure plate rather than by trapped chests. Thus, it would render that trap useless as well.

Personally, I would recommend looking into another type of Battle Towers mod, as I believe several exist for 1.16.5. This one seems badly designed, as it would break a normal loot container as well -- unless the original loot container was specifically blast proof?

**Comment by MystiaTech** [comment]
I will definitely look into finding a different mod. Thank you for taking the time to looking issue and resolving it quickly.

**Comment by noobanidus** [comment]
No worries, sorry I couldn't be more help!
